#define AK8963_INSTALLED
// #define HMC5883L_INSTALLED
#define MPU6500_INSTALLED

#define ACCELEROMETER_ORIENTATION(X,Y,Z) X,Y,Z
#define GYROSCOPE_ORIENTATION(X,Y,Z) X,Y,Z
#define MAGNETOMETER_ORIENTATION(X,Y,Z) X,Y,Z
